apiVersion: v1
kind: ConfigMap
metadata:
  name: order-manager-config
data:
  MONGO_CONNECTION_STRING: mongodb+srv://user-1:bg7YB8diWUk5QnG0@cluster0.ivyqtxs.mongodb.net/payment?retryWrites=true&w=majority&appName=Cluster0
